### ISSUE TITLE
So...how did it go?

### ISSUE THREAD

**Issue by easherma** [slathrop/vue-hugo-netlify-spa-demo#1]
Interested in this repo and it's concept. How would you say it went as a research project? Did you arrive at something useful and functional?

**Comment by slathrop** [comment]
Quite happy with the result. Used this approach on a customer site to collect data and store it in Git-backed flat file database. Even offered an open source CMS UI on top and read/write API access. See [here](https://github.com/railroadpm) for the repos... lots of good documentation in there too.

Despite this research being 3-4 years old now, I think the approach is still a sound one. I'd just update all of the libraries/frameworks/tools to the latest stable releases.
